openedx/openedx-aspects

.readthedocs.yaml
RTD deprectade defining the python version in the python top-level
setting.  It now has to be part of the build OS which is a required
setting.
I also added graphviz here in-case we want to add diagrams in the aspect
docs.
=> docs: Update RTD Config.

docs/reference/instructor_reports.rst, docs/reference/operator_reports.rst
Fleshes out the Instructor and Operator report reference documentation.
Uses existing "description" fields where found for charts and dashboards.
Ref: https://github.com/openedx/tutor-contrib-aspects/issues/169
=> docs: Adds reference docs for the Aspects dashboards and charts

docs/decisions/0001-open-analytics.rst, docs/decisions/0002_xapi.rst, docs/decisions/0003_superset.rst, docs/decisions/0004_clickhouse.rst, docs/decisions/0005_ralph.rst, docs/decisions/0006_areas_of_responsibility.rst
Updates the ADRs to replace references to "Open Analytics Reference System (OARS)" with "Aspects Analytics system (Aspects)".
=> fix: replaces references to OARS with Aspects in the ADRs

README.md, docs/decisions/0006_areas_of_responsibility.rst, docs/decisions/0008_project_structure.rst
Supersedes [ADR 6. Areas of Responsibility](https://docs.openedx.org/projects/openedx-aspects/en/latest/decisions/0006_areas_of_responsibility.html) with a new [ADR 8. Project structure]().
Also updates the README to provide links to the Tutor plugin and rendered documentation.
=> ADR 8. Project structure

docs/decisions/0009_pii.rst
Documents our decision to use PII in Aspects.
See rendered document here: [9. Personally-identifying information (PII)](https://docsopenedxorg--106.org.readthedocs.build/projects/openedx-aspects/en/106/decisions/0009_pii.html)
=> docs: adds ADR 9. Personally Identifying Information

docs/decisions/0010_localization.rst
Documents our decision to translate Superset assets.
View rendered page here: [10. Localization of user-facing content](https://docsopenedxorg--107.org.readthedocs.build/projects/openedx-aspects/en/107/decisions/0010_localization.html)
=> docs: Adds ADR 10. Localization

docs/decisions/0011_course_block_data.rst
Documents our decision to use an event sink to synchronize course and block data from Open edX to Clickhouse.
=> docs: Adds ADR 11. Course and block data

docs/decisions/0010_localization.rst
Addresses https://github.com/openedx/openedx-aspects/pull/107#discussion_r1458230708
=> docs: adds actual l10n alternative to ADR 10

docs/concepts/dbt.rst, docs/concepts/index.rst, docs/how-tos/dbt_extensions.rst
1. Adds [dbt concept documentation](https://docsopenedxorg--111.org.readthedocs.build/projects/openedx-aspects/en/111/concepts/dbt.html)
1. Updates the [dbt extension how-to](https://docsopenedxorg--111.org.readthedocs.build/projects/openedx-aspects/en/111/how-tos/dbt_extensions.html)
Closes https://github.com/openedx/openedx-aspects/issues/68
=> docs: adds DBT concept documentation

docs/decisions/0013_clickhouse_experimental.rst
Records the decision to avoid "experimental" features in Clickhouse, and to use "beta" features with caution.
=> docs: adds ADR 13. Clickhouse experimental and beta features

docs/how-tos/dbt_extensions.rst
This PR adds documentation for a new setting called DBT_SSH_KEY that allows to setup a private key to clone a private dbt repository.
=> docs: add dbt_ssh_key documentation

docs/how-tos/dbt_extensions.rst
Adds step-by-step instructions for creating and using a custom dbt package.
See the rendered [How to: Extending dbt](https://docsopenedxorg--190.org.readthedocs.build/projects/openedx-aspects/en/190/how-tos/dbt_extensions.html)
Closes https://github.com/openedx/openedx-aspects/issues/73
=> docs: enhancing the "How to extend dbt" page

docs/concepts/data_lifecycle_policy.rst, docs/concepts/index.rst
This PR adds documentation for the TTL configuration for ClickHouse tables.
Closes: https://github.com/openedx/tutor-contrib-aspects/issues/536
=> docs: add data lifecycly policy

docs/how-tos/dbt_extensions.rst
=> fix: dbt requirements have moved to aspects-dbt

docs/how-tos/superset_extra_assets.rst
Adding information to update how do do this, including the new (currently unreleased)  updates that should go out in 1.0.3: https://github.com/openedx/tutor-contrib-aspects/pull/881
=> docs: Update information on extending Superset assets

docs/administator/reference/index.rst
This PR fix a broken link to the production configuration in the technical documentation in the Aspects documentation.
=> docs: update link to production configuration

docs/technical_documentation/how-tos/production_configuration.rst
Enabling PII sharing for users inside `docs/technical_documentation/how-tos/production_configuration.rst` mentioned `ASPECTS_ENABLE_USER_PII`
https://docs.openedx.org/projects/openedx-aspects/en/latest/technical_documentation/how-tos/production_configuration.html#personally-identifiable-identification
instead of `ASPECTS_ENABLE_PII` that used in the plugin:
https://github.com/openedx/tutor-contrib-aspects/blob/984e63495abeb020fbd31f07e14dc8d0833d1ef6/tutoraspects/plugin.py#L52
This will take care of that and will add a small command instruction to enable it using tutor.
=> fix: wrong variable name to enable PII

docs/reference/learner_groups_dashboard.rst
=> docs: Clarify missing data

catalog-info.yaml
This PR adds the key to catalog-info so that we can tag a release automatically next time.
=> chore: Adds openedx release annotation to the catalog-info file.

docs/technical_documentation/how-tos/production_configuration.rst
Documents how `LANGUAGE_CODE` is used to initialize Superset's `BABEL_DEFAULT_LOCALE`, with instructions for how to customize `BABEL_DEFAULT_LOCALE` if needed.
Relates to: https://github.com/openedx/tutor-contrib-aspects/pull/1017
Part of: https://github.com/openedx/openedx-aspects/issues/298
Preview the changed section here: https://docsopenedxorg--308.org.readthedocs.build/projects/openedx-aspects/en/308/technical_documentation/how-tos/production_configuration.html#superset-localization
=> docs: adds docs for LANGUAGE_CODE and BABEL_DEFAULT_LOCALE

docs/technical_documentation/decisions/0009_pii.rst
This required some fair bit of sleuthing! These docs were actually moved to the edx-platform project in https://github.com/openedx/edx-documentation/pull/2257 so update to the new location.
=> docs: Update outdated link target URLs

catalog-info.yaml
This repo was previously tagged for release only to facilitate docs builds. As it is a transitive dependency, it should not be tagged for release. Please see https://github.com/openedx/docs.openedx.org/issues/941 for more detail.
=> build: Untag this repo for release

docs/technical_documentation/how-tos/index.rst, docs/technical_documentation/how-tos/superset_config_docker.rst
=> docs: Superset config overrides 

docs/reference/in_context_dashboards.rst
This will make docs cross referencing more flexible rather than having to hard-link to a document's name.
=> docs: Add crossreference for docs linking
